### ISSUE TITLE
Vertices copy: KeyError: 'edges.freestyle' on 2.67+, line 598

### ISSUE THREAD

**Issue by MondayPM** [dairin0d/cut-copy-paste#1]
Traceback (most recent call last):
  File "c:\3d\blender\scripts\addons\space_view3d_cut_copy_paste.py", line 786, in execute
    self.write_mesh(obj, stream)
  File "c:\3d\blender\scripts\addons\space_view3d_cut_copy_paste.py", line 598, in write_mesh
    serializer = serializers[seq_type + "." + k]
KeyError: 'edges.freestyle'

location: <unknown location>:-1

**Comment by dairin0d** [comment]
Fixed (in version 0.6.2).
